### ISSUE TITLE
afterChangeFired not fired

### ISSUE THREAD

**Issue by seyaobey** [MAMABA/editstrap#38]
I have written this [ related stackoverflow question ](http://stackoverflow.com/questions/43758639/editstrap-afterchangevalue-not-fired). I thought also to write it here maybe to your attention. I am intending to get this library and now I am testing it (trial) . **afterChangedValue is not fired** on successful value change. This is my code (very simple):
`$('#txt-control').editstrap({

    type: 'text',
    emptyText: 'Enter your name' ,
    afterChangeValue: function(editable,newValue){
         alert('Value has successfully changed');            
    }
})`

Another thing is that when I use the getValue method, I get an object and not the value:

`$('#txt-control').editstrap('getValue') --> returns object`

I have made sure that jquery is properly loaded and alsothe editstrap.js library

Obviously there is something I am missing here. And your help would be greatly appreciated

**Comment by MAMABA** [comment]
Hello,

What version of Editstrap do you use?
Can you please post your html and javascript code?

Thanks and regards,

**Comment by seyaobey** [comment]
Thanks for the answer. I just purchased the Developer License. And now it is working. I guess there might be some limitations on the trial version. Great library by the way.

**Comment by MAMABA** [comment]
OK. please feel free to contact me if you need any help.
