### ISSUE TITLE
Can't buy using PayPal on website

### ISSUE THREAD

**Issue by djpentz** [MAMABA/editstrap#39]
It gives me the popup to enter my email address, and click the button to buy with PayPal, and nothing happens. For some reason looking at my JS console, it makes a call to Facebook?!?1

**Comment by MAMABA** [comment]
Hello,

you can buy with sellfy https://sellfy.com/p/UDkr/

Regards

**Comment by djpentz** [comment]
Oh ok. I was just reporting it in case you wanted to fix it.
